# Generated by Django 3.2.13 on 2022-11-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=500)),
                ('vote_average', models.FloatField(default=0)),
            ],
        ),
    ]
