# Generated by Django 3.2.13 on 2022-11-20 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='movie_1_voters',
            field=models.ManyToManyField(default=None, related_name='voted_movies_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='movie_2_voters',
            field=models.ManyToManyField(default=None, related_name='voted_movies_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
