# Generated by Django 3.2.13 on 2022-11-20 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20221120_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='movie_1_voters',
            field=models.ManyToManyField(blank=True, related_name='voted_movies_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='movie_2_voters',
            field=models.ManyToManyField(blank=True, related_name='voted_movies_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='win_movies',
            field=models.ManyToManyField(blank=True, related_name='lose_movies', to='movies.Movie'),
        ),
    ]
