# Generated by Django 3.2.13 on 2022-11-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221120_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='voted_movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie'),
        ),
    ]
