# Generated by Django 3.2.13 on 2022-11-17 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='movie_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='movie_1_voters',
            field=models.ManyToManyField(related_name='voted_movies_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='movie_2',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='movie_2_voters',
            field=models.ManyToManyField(related_name='voted_movies_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='voted_movie',
            field=models.BooleanField(),
        ),
    ]
