# Generated by Django 3.2.13 on 2022-11-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20221117_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='match',
            name='movie_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_1', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='match',
            name='movie_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_2', to='movies.movie'),
        ),
    ]
